server:
  port: 8543

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
turbine:
  appConfig: activationService
  clusterNameExpression: new String('default')